{
  "schemaVersion": "1.0",
  "id": "",
  "name": "DLL Execution by A Possible MS Office Macro Malware",
  "description": "MS office application made a suspicious connection and executed a suspicious dll using system tool",
  "riskLevel": "medium",
  "scope": "endpoint",
  "enable": true,
  "rules": [
    {
      "id": "",
      "name": "Possible MS Office Macro Malware Executed Regsvr32",
      "score": 10
    }
  ],
  "threshold": {
    "targetScore": 10,
    "withinSeconds": 300,
    "dedupSeconds": 0
  },
  "requiredProducts": [
    [
      "sao"
    ]
  ],
  "tags": [
    "MITRE.T1218",
    "MITRE.T1559",
    "MITRE.T1574"
  ],
  "playbooks": [
    {
      "id": "bd6c9ef1-965d-4204-b9f2-d39003708f18",
      "name": "Default Playbook"
    }
  ],
  "visibleLevel": 51,
  "globalModel": true,
  "silent": true,
  "author": "anishimura",
  "team": "JP-TRC",
  "date": "2021/04/19",
  "lastUpdate": "2021-04-19T00:00:00.000Z"
}